<?php 

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\user\UserInterface;
use Drupal\file\Entity\File;

/**
 * ngt_inscription_help
 *
 * @param  mixed $route_name
 * @param  mixed $route_match
 * @return void
 */
function ngt_inscription_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
      // Main module help for the ngt_inscription module.
      case 'help.page.ngt_inscription':
          $output = '';
          $output .= t('<h3>' . 'About') . '</h3>';
          $output .= t('<p>' . 'Customización para evento de inscripción a cursos') . '</p>';
      return $output;

  default:
  }
}

/**
 * Implements hook_theme()
 */
function ngt_inscription_theme() {
  return [
    'inscription_button' => [
      'variables' => [
        'dataAngular' => NULL,
        'directive'  => NULL,
        'uuid' => NULL,
        'config' => NULL,
        'class' => NULL,
        'plugin_id' => NULL,
      ],
      'template' => 'block--inscription-button',
    ],
    'uninscription_button' => [
      'variables' => [
        'dataAngular' => NULL,
        'directive'  => NULL,
        'uuid' => NULL,
        'config' => NULL,
        'class' => NULL,
        'plugin_id' => NULL,
      ],
      'template' => 'block--uninscription-button',
    ],
    'render_my_courses' => [
      'variables' => [
        'dataAngular' => NULL,
        'directive'  => NULL,
        'uuid' => NULL,
        'config' => NULL,
        'class' => NULL,
        'plugin_id' => NULL,
        'data' => NULL,
      ],
      'template' => 'block--render-my-courses',
    ],
  ];
}